### ISSUE TITLE
Дисклеймер о предустановке драйвера loki. Иначе на сервере может не запуститься

### ISSUE THREAD

**Issue by NitaKai** [AlanLatte/Python#13]
docker plugin install  grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
<img width="827" alt="image" src="https://github.com/AlanLatte/Python/assets/32329170/3cb65830-f5f8-4498-9a62-ff4096228e21">

**Comment by AlanLatte** [comment]
убрал локи в v2.6
