### ISSUE TITLE
При авторизации используешь хеддеры, полностью игнорируя куксы. Возможно, лучше вернуть вариативность

### ISSUE THREAD

**Issue by NitaKai** [AlanLatte/Python#17]
<img width="1296" alt="image" src="https://github.com/AlanLatte/Python/assets/32329170/24fa855a-54c2-4026-9b14-f87d594d7c65">

**Comment by NitaKai** [comment]
<img width="1296" alt="image" src="https://github.com/AlanLatte/Python/assets/32329170/e2c59872-63b1-41ea-8713-bd29bc073035">
up

**Comment by AlanLatte** [comment]
Выпилил JWT.
